package com.spring.data.database.mybatis.mapper.database;

import com.spring.data.database.mybatis.model.ZmSystem;
import java.util.List;

public interface ZmSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_system
     *
     * @mbg.generated
     */
    int insert(ZmSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_system
     *
     * @mbg.generated
     */
    ZmSystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_system
     *
     * @mbg.generated
     */
    List<ZmSystem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZmSystem record);
}