logging:
  level: info
  file: log/model.log
server:
  port: 9002
  address: 192.168.99.28
spring:
  application:
    name: zm-study-service
eureka:
  client:
    service-url: http://192.168.99.28:8001/eureka/
