package com.spring.data.database.mybatis.model;

import java.io.Serializable;

public class HibernateSequence implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hibernate_sequence.next_val
     *
     * @mbg.generated
     */
    private Long nextVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hibernate_sequence
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hibernate_sequence.next_val
     *
     * @return the value of hibernate_sequence.next_val
     *
     * @mbg.generated
     */
    public Long getNextVal() {
        return nextVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hibernate_sequence.next_val
     *
     * @param nextVal the value for hibernate_sequence.next_val
     *
     * @mbg.generated
     */
    public void setNextVal(Long nextVal) {
        this.nextVal = nextVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hibernate_sequence
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nextVal=").append(nextVal);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}