logging:
  level: info
  file: log/web.log

server:
  port: 8081
  address: 192.168.99.28

spring:
  application:
    name: zm-study-web

#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.99.28:8001/eureka/

